M48
; DRILL file {KiCad (6.0.5)} date Thu Jan 26 23:57:37 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-26T23:57:37-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1300
%
G90
G05
T1
X5.9795Y-4.8331
X5.9795Y-5.2661
T2
X6.724Y-4.505
X6.724Y-5.305
X7.524Y-4.505
X7.524Y-5.305
T0
M30
